NUnitLite/TouchRunner/HttpTextWriter.cs, NUnitLite/TouchRunner/TouchOptions.cs, NUnitLite/TouchRunner/TouchRunner.cs
There is no public API to create raw sockets with watchOS, so
we can't use Tcp directly, thus the need for using Http.
=> Add a HttpTextWriter that can send logs over http.

Touch.Server/Main.cs
This seems to make our xcode8 based tests fully reliable on wrench.
It must be helping us bypass the bug that causes the deadlock if we
wait for the process to gracefully exit
=> wait longer as some tools take a while to exit

NUnitLite/TouchRunner/TouchOptions.cs, NUnitLite/TouchRunner/TouchRunner.cs
Users can either pass and option or set a env var to state that they want the logs to use the nunit xml format. This is useful in those cases when the  output wants to be parsed (example: jenkins bots).
=> Add xml output support

NUnitLite/TouchRunner/TouchRunner.cs
Ensure that if we try to close the write and it throws an exception we do not crash and clean the resource.
=> [TouchRunner] Fix CloseWriter

NUnitLite/TouchRunner/TouchRunner.cs
Extensions will automatically re-launch if they exit manually (or if they
crash), which means that every time a test run from an extension terminates,
iOS will re-launch it.
Unfortunately iOS will launch the extension with the same environment
variables, thus configuring the process to autorun / autoexit, which leads to
an infinite number of test runs (except that iOS detects extensions that
frequently exits and invalidates them after a while).
Fortunately, this second time we won't be able to connect to the test runner, so
we can use that to break the cycle.
=> [TouchRunner] Don't auto-exit if we couldn't connect to the test runner.

NUnitLite/TouchRunner/TouchRunner.cs
This might help us narrow down https://bugzilla.xamarin.com/show_bug.cgi?id=56162.
=> [TouchRunner] Print something before exiting.

NUnitLite/TouchRunner/TouchRunner.cs
depends on https://github.com/mono/NUnitLite/pull/7
=> [TouchRunner] do not use FinallyDelegate in Runner, because it requires remoting API to be available

NUnitLite/TouchRunner/TouchRunner.cs
The new improved logging adds this bit of info to the run logs:
```
2019-08-14 15:21:04.592 dont link[7054:2130112] TCP connection failed when selecting 'hostname': System.Net.Sockets.SocketException (0x80004005): No route to host
at System.Net.Sockets.TcpClient..ctor (System.String hostname, System.Int32 port) [0x0006d] in /Users/vidondai/Documents/xi-xcode11/xamarin-macios/external/mono/mcs/class/referencesource/System/net/System/Net/Sockets/TCPClient.cs:122 
at MonoTouch.NUnit.UI.BaseTouchRunner+<>c__DisplayClass55_2.<SelectHostName>b__0 (System.Object v) [0x00000] in /Users/vidondai/Documents/xi-xcode11/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs:204 
2019-08-14 15:21:04.592 dont link[7054:2130113] TCP connection failed when selecting 'hostname': …
```
=> Improve logging for failed TCP connections due to hostname

Touch.Server/Main.cs
After `12.14.0.114` there is no more `/Developer/MonoTouch` dir https://github.com/xamarin/xamarin-macios/commit/c66911641e518fd191246da7b72b7e3060d00550
=> Fallback to "modern" mtouch root if `MONOTOUCH_ROOT` is not set.

NUnitLite/TouchRunner/TestCaseElement.cs, NUnitLite/TouchRunner/TestElement.cs, NUnitLite/TouchRunner/TestSuiteElement.cs
Now we fully support light and dark modes. Before that we'd show the tests in black https://github.com/migueldeicaza/MonoTouch.Dialog/blob/98c2a56eaf37a483b47f12599675e41b91319d38/MonoTouch.Dialog/Elements.cs#L879 and that didn't play nice with dark mode (:
=> [TouchRunner] Fix colors for iOS 13 dark mode

.gitignore, Touch.Server/Main.cs
The current code includes a header with the log file and prevents the output from being processed in an automated build process.  By default, the header will continue to be included in the log file.
> -skipheader [Exclude the header from the log file (default: false)]
=> Included option to skip log file header

NUnitLite/TouchRunner/TcpTextWriter.cs, NUnitLite/TouchRunner/TouchOptions.cs, NUnitLite/TouchRunner/TouchRunner.cs
Using a tcp tunnel inverts the way we communicate with the device. We
move from a TcpClient to a TcpListener. In this case we need to wait
until we have a client connected that sends us a ping to start running
the tests.
This commit does not mean that we won't be able to use a normal tcp
conection, just means that if required, we can use a tunnel
=> [TCP] Add support to use a tcp tunnel.

NUnitLite/TouchRunner/TouchOptions.cs, NUnitLite/TouchRunner/TouchRunner.cs, NUnitLite/TouchRunner/TouchViewController.cs
Fixes several compiler warnings:
TouchRunner/TouchRunner.cs(508,32): warning CS3001: Argument type 'UIWindow' is not CLS-compliant
TouchRunner/TouchRunner.cs(516,33): warning CS3003: Type of 'TouchRunner.NavigationController' is not CLS-compliant
TouchRunner/TouchRunner.cs(526,27): warning CS3002: Return type of 'TouchRunner.GetViewController()' is not CLS-compliant
TouchRunner/TouchOptions.cs(146,27): warning CS3002: Return type of 'TouchOptions.GetViewController()' is not CLS-compliant
TouchRunner/TouchViewController.cs(43,23): warning CS3009: 'TouchViewController': base type 'DialogViewController' is not CLS-compliant
TouchRunner/TouchViewController.cs(45,43): warning CS3001: Argument type 'RootElement' is not CLS-compliant
=> Remove CLSCompliant attribute which causes compiler warnings.

NUnitLite/TouchRunner/TestCaseElement.cs
Otherwise the current element will show up as not executed when returning from the sub element.
=> [TouchRunner] Update the current element even if showing a sub element with failure info.

NUnitLite/TouchRunner/NUnitOutputTextWriter.cs, NUnitLite/TouchRunner/TestCaseElement.cs, NUnitLite/TouchRunner/TestElement.cs, NUnitLite/TouchRunner/TestRocks.cs, NUnitLite/TouchRunner/TestSuiteElement.cs, NUnitLite/TouchRunner/TouchRunner.cs, Touch.Client/Touch.Client.csproj, Touch.Unit.sln
This client can be used from .NET 5.
=> [Touch.Client] Add a client that uses MonoTouch.Dialog and NUnitLite from NuGet.

Touch.Client/Touch.Client-iOS.csproj, Touch.Client/Touch.Client-tvOS.csproj, Touch.Unit.sln
Also rename Touch.Client to Touch.Client-iOS, and make sure to use different
output and intermediate paths in the two project files, so that they don't
output files in the same directories.
=> Add tvOS version of Touch.Client.

NUnitLite/TouchRunner/TouchRunner.cs
* The full name is printed for the test suite
* The simple name is printed for each test fixture.
=> [TouchRunner] Improve name printing in NuGet mode.

NUnitLite/TouchRunner/TouchRunner.cs
For nested tests, where there's a single test for each nesting level, this
avoids having to drill down all the way to run the actual test.
=> [TouchRunner] Always show 'Run all'.

NUnitLite/TouchRunner/TestCaseElement.cs, NUnitLite/TouchRunner/TestSuiteElement.cs, NUnitLite/TouchRunner/TouchRunner.cs
Only update the UI for a single test after we're notified that the test has
finished running. This is a step towards making async tests work properly,
where we can't assume that the test has finished after calling Run.
Also we only want to show more details for a test if we ran that test as a
result of tapping on it.
=> [TouchRunner] Only update the UI for a single test after the test has finished running.

NUnitLite/TouchRunner/TouchRunner.cs
Updated versions of NUnit will capture Console.Out during a test run. We want
to show it in the Console, so write it there when the test has finished.
I couldn't find a way to tell NUnit to not capture Console.Out in the first place.
=> [TouchRunner] Print test output to the console.

NUnitLite/TouchRunner/TouchRunner.cs
It's not possible to use a single NUnitTestAssemblyRunner instance for
multiple assemblies, so we need to create one for each assembly we want to
test.
=> [TouchRunner] Fix running multiple test assemblies in NUnitLite mode.

NUnitLite/TouchRunner/TouchOptions.cs
Parse command line options like we parse the corresponding environment
variables (case insensitively)
Also fix actually passing values to a few arguments.
=> [TouchOptions] Fix a few issues related to command-line parsing.

NUnitLite/TouchRunner/TouchOptions.cs
The property should probably be renamed, but that's for another time.
=> [TouchRunner] Fix network logging to log if we're logging to a file even if EnableNetwork is false.

NUnitLite/TouchRunner/ExcludedCategoryFilter.cs, NUnitLite/TouchRunner/TouchRunner.cs, Touch.Client/dotnet/iOS/Touch.Client-iOS.dotnet.csproj, Touch.Client/dotnet/tvOS/Touch.Client-tvOS.dotnet.csproj, Touch.Client/iOS/Touch.Client-iOS.csproj, Touch.Client/macOS/full/Touch.Client-macOS-full.csproj, Touch.Client/macOS/mobile/Touch.Client-macOS-mobile.csproj, Touch.Client/tvOS/Touch.Client-tvOS.csproj, Touch.Client/watchOS/Touch.Client-watchOS.csproj
The NUnitLite API to create test filters is very rudimentary (either subclass
TestFilter, or have NUnitLite create the filter based on an xml string), so we
can at least make it easy for consumers to exclude tests based on categories,
which we need to be able to do for our tests anyway.
=> [Touch.Client] Add API to exclude tests based on categories.

Touch.Client/iOS/Touch.Client-iOS.csproj, Touch.Client/macOS/full/Touch.Client-macOS-full.csproj, Touch.Client/macOS/mobile/Touch.Client-macOS-mobile.csproj, Touch.Client/tvOS/Touch.Client-tvOS.csproj, Touch.Client/watchOS/Touch.Client-watchOS.csproj
Make sure any possible project configuration (not only Debug and Release) has
an OutputPath set and the NUNITLITE_NUGET variable set.
Both are needed to build the projects, and we use custom configurations when
building some of our test projects (such as Debug[32|64] for instance).
=> [Touch.Client] Adjust project configurations.

NUnitLite/TouchRunner/TouchRunner.cs
If our filter subclasses TestFilter and overrides TestFilter.Match, we must
also call TestFilter.Match for any nested filters to get the correct behavior.
=> [TouchRunner] Fix test filtering.

Touch.Server/Main.cs
* MTouch requires `--target-framework` after `13.20`, but when it calls `mlaunch` forwarding all the arguments, `mlaunch` doesn't handle the `--target-framework` parameter.
=> Call `mlaunch` instead of `mtouch`

Touch.Client/dotnet/iOS/Touch.Client-iOS.dotnet.csproj, Touch.Client/dotnet/tvOS/Touch.Client-tvOS.dotnet.csproj
.NET 5 has added support for our TargetFrameworks, so let's start using them.
=> [Touch.Client] Use the right TargetFrameworks.

Touch.Client/dotnet/iOS/Touch.Client-iOS.dotnet.csproj, Touch.Client/dotnet/macOS/Touch.Client-macOS.dotnet.csproj, Touch.Client/dotnet/tvOS/Touch.Client-tvOS.dotnet.csproj, Touch.Client/dotnet/watchOS/Touch.Client-watchOS.dotnet.csproj
This is the desired Sdk, 'Microsoft.<platform>.Sdk' was temporary (and now we
don't need it that way anymore).
=> [Touch.Client] Use 'Microsoft.NET.Sdk' instead of 'Microsoft.<platform>.Sdk'.

NUnitLite/TouchRunner/TouchOptions.cs, NUnitLite/TouchRunner/TouchRunner.cs, NUnitLite/TouchRunner/TouchViewController.cs
```
/Users/poupou/git/xamarin/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs(686,32): warning CS3001: Argument type 'UIWindow' is not CLS-compliant
/Users/poupou/git/xamarin/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs(694,33): warning CS3003: Type of 'TouchRunner.NavigationController' is not CLS-compliant
/Users/poupou/git/xamarin/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs(704,27): warning CS3002: Return type of 'TouchRunner.GetViewController()' is not CLS-compliant
/Users/poupou/git/xamarin/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchOptions.cs(164,27): warning CS3002: Return type of 'TouchOptions.GetViewController()' is not CLS-compliant …
```
=> Fix C# compiler CLS-compliant warnings

Touch.Server/Main.cs
Because the ip, port and logpath options were missing `=` at the end of their names, you couldn't actually pass any values for them. If you tried, the string values for the options would be equal to their names (rather than what the user provided), and then the parsing failures for those strings would be silently ignored.
Additionally, after the `IPAddress` was successfully parsed, we ignored the result. This resulted in `listener.Address` being null, which eventually led to a crash once the listener was started. I fixed this as well.
In addition to adding the `=` to each option, I also changed the parsing from `TryParse` to `Parse` so that invalid option values will fail with an exception. This is similar to how the `TimeSpan` options are already being handled, but I wasn't sure if it …
=> [Touch.Server] Fix parsing of -address, -port and -logpath options

NUnitLite/TouchRunner/MacRunner.cs
Try to exit the NSApplication run loop nicely, by calling NSApplication.Stop.
The problem is that there seems to be certain requirements for stopping the
NSApplication: one being that apparently there must be a window around. So
create a window (that shows up in the background). Then at the end we have to
post something to the event loop after calling Stop (because calling Stop
apparently only sets a flag that's checked after processing an event). And
just in case seomthing goes wrong, try two different ways of posting events to
the event loop.
=> [TouchRunner] Try to make MacRunner exit nicely.

Touch.Client/dotnet/MacCatalyst/Touch.Client-MacCatalyst.dotnet.csproj
=> [Touch.Client] There's no need to include Xamarin.iOS in Mac Catalyst projects.

NUnitLite/TouchRunner/TouchRunner.cs
Fixes this compiler warning:
> warning CS0618: 'NSString.FromHandle(IntPtr)' is obsolete: 'Use of 'CFString.FromHandle' offers better performance.'
=> [TouchRunner] Use CFString.FromHandle instead of NSString.FromHandle.

NUnitLite/TouchRunner/MacRunner.cs, NUnitLite/TouchRunner/TouchRunner.cs
Fixes this warning:
xamarin-macios/tests/common/mac/MacMain.cs(24,26): warning CA1416: This call site is reachable on: 'macOS/OSX' 10.11 and later. 'MacRunner.MainAsync(IList<string>, bool, Action<int>, params Assembly[])' is only supported on: 'macOS/OSX' 12.0 and later.
=> [MacRunner] Add availability attribute to avoid a compiler warning.

Touch.Client/dotnet/MacCatalyst/Touch.Client-MacCatalyst.dotnet.csproj, Touch.Client/dotnet/iOS/Touch.Client-iOS.dotnet.csproj, Touch.Client/dotnet/macOS/Touch.Client-macOS.dotnet.csproj, Touch.Client/dotnet/tvOS/Touch.Client-tvOS.dotnet.csproj
This way we'll target net6.0-* when building with .NET 6, and net7.0-* when
building with .NET 7.
=> [Touch.Client] Use 'BundledNETCoreAppTargetFrameworkVersion' to specify the .NET version in the project files.

NUnitLite/TouchRunner/TouchRunner.cs
Hopefully this will make sure console output doesn't disappear into the void.
=> [TouchRunner] Flush the console before exiting.

Touch.Client/dotnet/MacCatalyst/Touch.Client-MacCatalyst.dotnet.csproj, Touch.Client/dotnet/iOS/Touch.Client-iOS.dotnet.csproj, Touch.Client/dotnet/macOS/Touch.Client-macOS.dotnet.csproj, Touch.Client/dotnet/tvOS/Touch.Client-tvOS.dotnet.csproj
This reverts commit be3a8d0855b8291848d02c9c9d99748cb41c56c2.
It won't be needed, using 'net6.0-*' will continue to work in .NET 7+.
=> Revert "[Touch.Client] Use 'BundledNETCoreAppTargetFrameworkVersion' to specify the .NET version in the project files. (#113)"

NUnitLite/TouchRunner/TouchRunner.cs
This PR adds a workaround to support NativeAOT runtime with Xamarin.
The limitation comes from the unsupported or limited support for the following properties on `Assembly` type with NativeAOT
- `CodeBase` - unsupported feature - throws with: https://github.com/dotnet/runtime/blob/588dcd7a29f109daae2d8c999322acd8e853a8c6/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Reflection/Runtime/General/ThunkedApis.cs#L70-L78
- `Location` - somewhat supported - empty string: https://github.com/dotnet/runtime/blob/588dcd7a29f109daae2d8c999322acd8e853a8c6/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Reflection/Runtime/General/ThunkedApis.cs#L66
Both properties do not seem to make sense with NativeAOT, as the assembly is not preserved in its original format.
These limitations …
=> Always use NUnitTestAssemblyRunner's Load overload with the assembly name
